# Generated by Django 4.2 on 2025-03-21 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MibtTestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('personality_type', models.CharField(max_length=4)),
                ('personality_category', models.CharField(choices=[('analyst', '分析型人格'), ('diplomat', '外交型人格'), ('sentinel', '哨兵型人格'), ('explorer', '探索型人格')], max_length=20)),
                ('introversion_score', models.IntegerField(default=0)),
                ('extroversion_score', models.IntegerField(default=0)),
                ('intuition_score', models.IntegerField(default=0)),
                ('sensing_score', models.IntegerField(default=0)),
                ('thinking_score', models.IntegerField(default=0)),
                ('feeling_score', models.IntegerField(default=0)),
                ('judging_score', models.IntegerField(default=0)),
                ('perceiving_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mibt_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
