import { HomeContainer } from '@/container/home-contanier';
import { Providers } from '@/provider/providers';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import 'react-photo-view/dist/react-photo-view.css';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='zh-CN' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <HomeContainer>{children}</HomeContainer>
        </Providers>
      </body>
    </html>
  );
}
