# Generated by Django 4.2 on 2025-04-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_postreport_delete_sensitiveword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postattachment',
            name='image',
        ),
        migrations.AddField(
            model_name='postattachment',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='post_attachments'),
        ),
        migrations.AddField(
            model_name='postattachment',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
    ]
