# Generated by Django 4.2 on 2025-04-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_remove_postattachment_image_postattachment_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postattachment',
            name='media',
        ),
        migrations.RemoveField(
            model_name='postattachment',
            name='media_type',
        ),
        migrations.AddField(
            model_name='postattachment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_attachments'),
        ),
    ]
